rbac:
  create: true
resourcesToWatch:
  deployment: false
  replicationcontroller: false
  replicaset: false
  daemonset: false
  services: false
  pod: false
  job: false
  node: true
  clusterrole: false
  clusterrolebinding: false
  serviceaccount: false
  persistentvolume: false
  namespace: true
  secret: false
  configmap: false
  ingress: false
  coreevent: false
  event: false
slack:
  enabled: false
webhook:
  enabled: true
  url: 'http://webhook-create-namespace-aap.apps.ricky-dev.ocp4.testing.ansible.com'
