rbac:
  create: true
resourcesToWatch:
  deployment: true
  replicationcontroller: false
  replicaset: false
  daemonset: false
  services: true
  pod: true
  job: false
  node: true
  clusterrole: false
  clusterrolebinding: false
  serviceaccount: false
  persistentvolume: true
  namespace: true
  secret: false
  configmap: false
  ingress: false
  coreevent: false
  event: false
slack:
  enabled: false
webhook:
  enabled: true
  url: 'http://webhook-debug-aap.apps.ricky-dev.ocp4.testing.ansible.com'
