- name: Listen for newly added resources
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Configure default quota on new namespace
      condition:
        all:
         - event.payload.eventmeta.kind == 'Namespace'
         - event.payload.eventmeta.reason == 'Created'
      action:
        run_job_template: 
          name: "Configure Namespace Quota"
          organization: "Default"
          job_args:
            extra_vars:
              namespace: "{{ event.payload.eventmeta.name }}"
