- hosts: all

  tasks:
    - ansible.builtin.debug:
        msg: '{{ ansible_eda }}'
    - kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            namespace: '{{ ansible_eda.events.m_1.payload.eventmeta.name }}'
            name: namespace-quota
          spec:
            hard:
              requests.cpu: "1"
              requests.memory: 1Gi
              limits.cpu: "2"
              limits.memory: 2Gi
