- hosts: all
  vars:
    namespace: "{{ ansible_eda.event.payload.eventmeta.name }}"
  tasks:
    - ansible.builtin.debug:
        msg: '{{ namespace }}'
    - kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            namespace: lol
            name: namespace-quota
          spec:
            hard:
              requests.cpu: "1"
              requests.memory: 1Gi
              limits.cpu: "2"
              limits.memory: 2Gi
